### ISSUE TITLE
Implicit not being imported

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11798]
## Compiler version

3.0.0-RC1

```
stdlibExtJVM> show Test / scalacOptions
[info] * -deprecation
[info] * -unchecked
[info] * -feature
[info] * -language:postfixOps
[info] * -language:implicitConversions
[info] * -language:higherKinds
[info] * -language:existentials
[info] * -source:3.0-migration
[info] * -Ykind-projector
```

## Minimized code

Here I'm importing my `TestUtil._` but `TestUtil.scalazEqualFromUnivEq` isn't importing:

```Scala
import japgolly.microlibs.testutil.TestUtil._

val x = japgolly.microlibs.testutil.TestUtil.scalazEqualFromUnivEq[Int] // ok
val y = scalazEqualFromUnivEq[Int] // error
```

## Output

```scala
[error] 8 |val y = scalazEqualFromUnivEq[Int]
[error]   |        ^^^^^^^^^^^^^^^^^^^^^
[error]   |        Not found: scalazEqualFromUnivEq
```

## Expectation

It should compile.

## Reproduction

```
cd /tmp
git clone https://github.com/japgolly/microlibs-scala.git
cd microlibs-scala
git checkout bug/import
sbt stdlibExtJVM/test:compile
```

**Comment by nicolasstucki** [comment]
This was probably fixed in #11591

**Comment by japgolly** [comment]
The problem still persists with Scala 3.0.0-RC2-bin-20210317-758782a-NIGHTLY so #11591 doesn't seem to have fixed this.

**Comment by nicolasstucki** [comment]
@japgolly could you minimize it?

**Comment by julienrf** [comment]
Shouldn’t you `import japgolly.microlibs.testutil.TestUtil.given`?

**Comment by japgolly** [comment]
@julienrf Shouldn't have to with `-source:3.0-migration`. I'm trying to cross-compile code for Scala 2 and Scala 3.

**Comment by smarter** [comment]
Are you sure this is supposed to work? When I grep for `scalazEqualFromUnivEq` in the branch you linked to I get:
```scala
test-util/shared/src/main/scala/japgolly/microlibs/testutil/TestUtil.scala
4:import japgolly.univeq.UnivEqScalaz.scalazEqualFromUnivEq

stdlib-ext/shared/src/test/scala/japgolly/microlibs/stdlib_ext/ExtractorsTest.scala
7:val x = japgolly.microlibs.testutil.TestUtil.scalazEqualFromUnivEq[Int]
8:val y = scalazEqualFromUnivEq[Int]
```

So TestUtil isn't defining scalazEqualFromUnivEq.

**Comment by japgolly** [comment]
Ah I'm so sorry for dropping the ball on this one. I raised over 100 tickets at that time and this one dropped through my fingers. I'll get back on this next week.

**Comment by japgolly** [comment]
Tried again with 3.0.0 final and this works now

**Comment by som-snytt** [comment]
I was going to comment yesterday that I also tried it the example project successfully. I didn't get around to clarifying anything because I was lost in the gollyverse, which is bigger on the inside than it looks from without.

To pick up the ball metaphor, the previous discussion is like golf when one goes missing.
