### ISSUE TITLE
Problems with jsoniter compilation after 3.3.1

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19098]
## Compiler version

Everything after 3.3.1.
`3.3.2-RC1-bin-20230530-28915c4-NIGHTLY` - `3.3.2-RC1-bin-20230705-13f877b-NIGHTLY` - `xcheck-macros` error
from `3.3.2-RC1-bin-20230706-3ae2dbf-NIGHTLY` - type crash

## Reproduction

```sh
git clone --branch v2.24.4 --depth 1 https://github.com/plokhotnyuk/jsoniter-scala.git
cd jsoniter-scala
sbt
++3.3.2-RC1-bin-20230705-13f877b-NIGHTLY!
jsoniter-scala-macrosJVM/Test/compile
```

## Output (click arrow to expand)
Up to `3.3.2-RC1-bin-20230705-13f877b-NIGHTLY` - `xcheck-macros` assertion fail about missing position
From ` 3.3.2-RC1-bin-20230706-3ae2dbf-NIGHTLY`:

<details>

```
[error] java.lang.AssertionError: assertion failed
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
[error] dotty.tools.dotc.core.Types$LazyRef.ref(Types.scala:3111)
[error] dotty.tools.dotc.core.Types$Type.dealias1(Types.scala:1433)
[error] dotty.tools.dotc.core.Types$Type.dealias(Types.scala:1441)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:171)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:169)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.op$proxy25$1(Types.scala:6246)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$3(Types.scala:6246)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6250)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:198)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:169)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6284)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:198)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:169)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6284)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:198)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:172)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:169)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.op$proxy25$1(Types.scala:6246)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$3(Types.scala:6246)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6250)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:198)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:169)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6284)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:198)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:169)
[error] dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6284)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:198)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:172)
[error] dotty.tools.dotc.typer.Inferencing$IsFullyDefinedAccumulator.apply(Inferencing.scala:169)
[...]

```
</details>

**Comment by nicolasstucki** [comment]
The missing position was fixed in #18178.

**Comment by nicolasstucki** [comment]
I have no insight on the `LazyRef.ref` assertion failure.

**Comment by WojciechMazur** [comment]
The compilation crash is still present in the latest 3.5.0-RC1-nightly. The code that triggers the crash is a single test https://github.com/plokhotnyuk/jsoniter-scala/blob/84d57daeada31c0cce2631489e6d7c71e57be37e/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerNewTypeSpec.scala#L97-L205 
One of the reasons for the crash is the used recursive match type - this kind of constructs are not allowed. It's reproduction can be found in here https://github.com/scala/scala3/issues/18257#issuecomment-1777010537 - however what's important in this form it leads to infinite loop instead of crash.
The one thing that Scala compiler should do is to detect and break the cycle early. The recursive match type detection works only for simpler types, but in the complex ones, as the one in jsoniter, we never get any hints from compiler what goes wrong.

**Comment by plokhotnyuk** [comment]
I’ve removed the test that used recursion in pattern matching from the jsoniter-scala test suite.

But instead I've added a couple of other tests with:
1) [recursive tuple types](https://github.com/plokhotnyuk/jsoniter-scala/blob/b83c80549d28886d1c410993f31545e790b865a2/jsoniter-scala-next-tests/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerNamedTupleSpec.scala#L85-L86) that works fine with Scala 3.7.3
2) [fix-point recursion on types](https://github.com/plokhotnyuk/jsoniter-scala/blob/b83c80549d28886d1c410993f31545e790b865a2/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerNewTypeSpec.scala#L71-L105) that works even with Scala 3.3.6

Hopefully, this is the compiler’s intended behavior.

**Comment by soronpo** [comment]
OOM minimization
```scala
import scala.collection.mutable

type Rec[JA[_], JO[_], A] = A match {
  case Int => Int | JA[Rec[JA, JO, Int]] | JO[Rec[JA, JO, Int]]
  case _ => A | JA[Rec[JA, JO, A]] | JO[Rec[JA, JO, A]]
}
type Json = Rec[List, [A] =>> Map[String, A], Int]

def arr(values: Json*): Json = mutable.ArrayBuffer[Json](values*)

val x = arr(1)
```
