### ISSUE TITLE
Flatten lifts out anonymous module vals without making sure that lifted names do not conflict

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#415]
Shown by `./tests/pos/zoo.scala`
```
checking ./tests/pos/zoo.scala after phase TreeTransform:{LazyVals, seqLiterals, intercepted, literalize, getters, elimByName, resolveSuper}
checking ./tests/pos/zoo.scala after phase TreeTransform:{mixin, memoize, capturedVars, constructors}
checking ./tests/pos/zoo.scala after phase TreeTransform:{lambdaLift, flatten, restoreScopes}
[error] module val defined twice module $anon 9922 9917
[error] module val defined twice module $anon 9927 9922
[error] module val defined twice module $anon 9932 9927
```

**Comment by odersky** [comment]
This should be solved by #420 @DarkDimius can you check and close the issue if that's the case?

**Comment by DarkDimius** [comment]
After applying 7b6964ae3408d2a4676d7d5af884238b44071fba the problem persists.

**Comment by odersky** [comment]
I agree the problem persists. After some investigation, it looks like the test checks the wrong condition. Module vals are not lifted out; they remain in the scope where they were defined first. So there's no reason why they should have unique names.

**Comment by DarkDimius** [comment]
The check suggests that they start to clash with names only after flatten, that is, before flatten the names were unique. If they are not lifted out, what made them clash?

**Comment by odersky** [comment]
This: (in TreeChecker)

*    if* (*this*.flatClasses || !(sym.isAnonymousFunction ||
sym.isAnonymousClass || sym.isAnonymousModuleVal))

        printError(s"$typ defined twice $sym ${sym.id} ${registry(name).id}"
)

On Sun, Mar 22, 2015 at 7:00 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> The check suggests that they start to clash with names only after flatten,
> that is, before flatten the names were unique. If they are not lifted out,
> what made them clash?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/415#issuecomment-84667413>.
>



-- 
Martin Odersky
EPFL

**Comment by DarkDimius** [comment]
ahh, I get it.
I'll remove this check.
Thanks for investigation.
