### ISSUE TITLE
Incorrect highlight color in REPL for Singleton types in Union types

### ISSUE THREAD

**Issue by newca12** [lampepfl/dotty#6574]
![Capture d’écran 2019-05-27 à 23 27 31](https://user-images.githubusercontent.com/543542/58440007-90f7e580-80d7-11e9-9c5a-2353ffabdeea.png)

**Comment by allanrenucci** [comment]
The syntax highlighter gets confused because `Int(1) | Int(2)` is not valid syntax. Fixing #3683 should resolve this issue as well.

**Comment by newca12** [comment]
Ya fix the example but REPL, singleton types and union types  still not made good bedfellows
scala> :type a
Int(31m10m) | Int(31m00m)
